-- Create users/roles table
USE MUSEUM_DATABASE;
CREATE TABLE IF NOT EXISTS Users (
  User_ID INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  Role ENUM('admin','guest') NOT NULL DEFAULT 'guest',
  Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
