-- Create bookings table to replace legacy visitor table
USE MUSEUM_DATABASE;

CREATE TABLE IF NOT EXISTS bookings (
  Booking_ID INT AUTO_INCREMENT PRIMARY KEY,
  User_ID INT NOT NULL,
  Ticket_Serial BIGINT NOT NULL,
  Quantity INT NOT NULL DEFAULT 1,
  Purchase_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (User_ID) REFERENCES users(User_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (Ticket_Serial) REFERENCES tickets(Serial) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
