ALTER TABLE `tickets` ADD COLUMN `Event_ID` INT(11) NULL;
ALTER TABLE `tickets` ADD CONSTRAINT `fk_tickets_event` FOREIGN KEY (`Event_ID`) REFERENCES `events` (`Event_ID`) ON DELETE CASCADE ON UPDATE CASCADE;
